sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #download gcloud sdk and install it locally on our instance that assigned to us by travis CI
  - source $HOME/google-cloud-sdk/path.bash.inc # look at the default install dic and source the file
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file service-account.json 
  - gcloud config set project multi-k8s-319212 #which project we want to work on
  - gcloud config set compute/zone europe-central2-c #defining zone
  - gcloud container clusters get-credentials multi-cluster #which cluster its working with
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t burakaraca/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true burakaraca/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master